org.gradle.jvmargs=-Xmx3G

# Project
version=1.0.0
group=com.movtery.betterf1

# Mod
mod_id=betterf1
mod_name=Better F1
mod_author=UltimateBoomer, MovTery, DHJComical
license=MIT
description=Hide parts of your HUD using F1.

# Minecraft / Forge - https://files.minecraftforge.net/net/minecraftforge/forge/index_1.19.2.html
minecraft_version=1.19.2
forge_version=43.5.0
